// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace PhotoStock.API.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20220728220034_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AuthorId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfRegistration")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1996, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            DateOfRegistration = new DateTime(2022, 7, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            FirstName = "Sanjar",
                            LastName = "Tursunov",
                            NickName = "Sancho"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1999, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            DateOfRegistration = new DateTime(2022, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            FirstName = "Shokhzod",
                            LastName = "Azamatov",
                            NickName = "AshoT"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2000, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            DateOfRegistration = new DateTime(2022, 7, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            FirstName = "Aziz",
                            LastName = "Kholkazakov",
                            NickName = "ICloud"
                        });
                });

            modelBuilder.Entity("Entities.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PhotoId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<int>("NumberOfSales")
                        .HasColumnType("int");

                    b.Property<string>("OriginalSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 2,
                            Cost = 100m,
                            DateOfCreation = new DateTime(2022, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Link = "C:\\Users\\ashot\\source\\repos\\PhotoStockSolution\\PhotoStock.API\\Images\\Furniture\\Furniture1.png",
                            Name = "Antaliya",
                            NumberOfSales = 5,
                            OriginalSize = "1280 x 720",
                            Rating = 2
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 3,
                            Cost = 120m,
                            DateOfCreation = new DateTime(2022, 7, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Link = "C:\\Users\\ashot\\source\\repos\\PhotoStockSolution\\PhotoStock.API\\Images\\Furniture\\Furniture2.png",
                            Name = "Monaliza",
                            NumberOfSales = 10,
                            OriginalSize = "1280 x 720",
                            Rating = 3
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Cost = 95m,
                            DateOfCreation = new DateTime(2022, 7, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Link = "C:\\Users\\ashot\\source\\repos\\PhotoStockSolution\\PhotoStock.API\\Images\\Furniture\\Furniture3.png",
                            Name = "Madonna",
                            NumberOfSales = 3,
                            OriginalSize = "1280 x 720",
                            Rating = 1
                        });
                });

            modelBuilder.Entity("Entities.Models.Text", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TextId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<int>("NumberOfSales")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Texts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 2,
                            Cost = 50m,
                            DateOfCreation = new DateTime(2022, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "MY5 Chanel",
                            Note = "This is a great chanel",
                            NumberOfSales = 3,
                            Rating = 2
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 3,
                            Cost = 200m,
                            DateOfCreation = new DateTime(2022, 7, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "FCB",
                            Note = "professional football club",
                            NumberOfSales = 18,
                            Rating = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
